---
repos:
  - repo: https://github.com/rhysd/actionlint
    rev: v1.6.22
    hooks:
      - id: actionlint

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: mixed-line-ending
      - id: sort-simple-yaml
