---
name: Docker Image CI

on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        distro:
          - leap
          - tumbleweed
    
    defaults:
      run:
        working-directory: ${{ matrix.distro }}

    steps:
      - uses: actions/checkout@v3

      - uses: hadolint/hadolint-action@v3.0.0
        with:
          ignore: DL3007,DL3037,DL3013,DL3035
  
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        distro:
          - leap
          - tumbleweed

    defaults:
      run:
        working-directory: ${{ matrix.distro }}

    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Install Goss
        uses: e1himself/goss-installation-action@v1.1.0
      
      - name: Build and Export
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/amd64
          push: false
          load: true
          tags: "artis3n/docker-opensuse-${{ matrix.distro }}-ansible:test"
          cache-from: type=gha
          cache-to: type=gha,mode=max
      
      - name: Test the Docker image
        run: dgoss run -it --rm --privileged --volume=/sys/fs/cgroup:/sys/fs/cgroup:ro artis3n/docker-opensuse-${{ matrix.distro }}-ansible:test
